Add reviews amount
WebAhead/wajjbat-frontend pull request #25
Opened 2020-03-23 15:02 UTC by MahmodMhamed

Add reviewrs num near to ratings rel #4

2020-03-23 17:38 UTC, Karyum requested changes
I would rather have the "Based on x reviews" in the reviews tab, to be exact check  the pic below
![Screenshot from 2020-03-23 19-23-25](https://user-images.githubusercontent.com/24195641/77344879-7e246080-6d3c-11ea-9ed9-530dda1d2d0b.png)
with the same css styling

2020-03-23 17:38 UTC, Karyum commented on src/pages/BusinessPage/components/BusinessDetails/index.jsx
> +                    <span className={style['reviewrs-count']}>Based on {businessData.reviews.length}  reviews</span>
so this is hard coded text, if you saw all over the app we use `<FormattedMessage />` component, which comes from `react-intl` that translates our app.

[here is a link for the documention of <FormattedMessage />](https://github.com/formatjs/react-intl/blob/master/docs/Components.md#formattedmessage)

at the end it should look something like this
```html
<FormattedMessage
  id="Reviews amount"
  values={{
    reviews: businessData.reviews.length,
  }}
/>
```

2020-03-24 10:55 UTC, MahmodMhamed commented
Fixed, the message has been added a FormattedMessage component at the place you wanted and it is also support ar & en.

2020-03-24 10:55 UTC, Karyum approved these changes

2020-03-24 10:59 UTC, merged